//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corral.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corral.Desktop.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corral.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corral Manager.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateZone_Cancel {
            get {
                return ResourceManager.GetString("CreateZone_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string CreateZone_ColorLabel {
            get {
                return ResourceManager.GetString("CreateZone_ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        public static string CreateZone_Creating {
            get {
                return ResourceManager.GetString("CreateZone_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zone.
        /// </summary>
        public static string CreateZone_Header {
            get {
                return ResourceManager.GetString("CreateZone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONE NAME.
        /// </summary>
        public static string CreateZone_NameLabel {
            get {
                return ResourceManager.GetString("CreateZone_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPACITY.
        /// </summary>
        public static string CreateZone_OpacityLabel {
            get {
                return ResourceManager.GetString("CreateZone_OpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Zone.
        /// </summary>
        public static string CreateZone_Submit {
            get {
                return ResourceManager.GetString("CreateZone_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zone.
        /// </summary>
        public static string CreateZone_Title {
            get {
                return ResourceManager.GetString("CreateZone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditZone_Cancel {
            get {
                return ResourceManager.GetString("EditZone_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string EditZone_ColorLabel {
            get {
                return ResourceManager.GetString("EditZone_ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Zone.
        /// </summary>
        public static string EditZone_Header {
            get {
                return ResourceManager.GetString("EditZone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONE NAME.
        /// </summary>
        public static string EditZone_NameLabel {
            get {
                return ResourceManager.GetString("EditZone_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPACITY.
        /// </summary>
        public static string EditZone_OpacityLabel {
            get {
                return ResourceManager.GetString("EditZone_OpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string EditZone_Saving {
            get {
                return ResourceManager.GetString("EditZone_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditZone_Submit {
            get {
                return ResourceManager.GetString("EditZone_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Zone.
        /// </summary>
        public static string EditZone_Title {
            get {
                return ResourceManager.GetString("EditZone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occurred. The application will close..
        /// </summary>
        public static string Error_Fatal {
            get {
                return ResourceManager.GetString("Error_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error — Corral Manager.
        /// </summary>
        public static string Error_FatalTitle {
            get {
                return ResourceManager.GetString("Error_FatalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred:.
        /// </summary>
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error — Corral Manager.
        /// </summary>
        public static string Error_UnexpectedTitle {
            get {
                return ResourceManager.GetString("Error_UnexpectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Nav_Help {
            get {
                return ResourceManager.GetString("Nav_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string Nav_Zones {
            get {
                return ResourceManager.GetString("Nav_Zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        public static string Overlay_AddFile {
            get {
                return ResourceManager.GetString("Overlay_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder....
        /// </summary>
        public static string Overlay_AddFolder {
            get {
                return ResourceManager.GetString("Overlay_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program....
        /// </summary>
        public static string Overlay_AddProgram {
            get {
                return ResourceManager.GetString("Overlay_AddProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string Overlay_BrowseFile {
            get {
                return ResourceManager.GetString("Overlay_BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        public static string Overlay_BrowseFolder {
            get {
                return ResourceManager.GetString("Overlay_BrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a program.
        /// </summary>
        public static string Overlay_BrowseProgram {
            get {
                return ResourceManager.GetString("Overlay_BrowseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Overlay_Delete {
            get {
                return ResourceManager.GetString("Overlay_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Overlay_FilterAllFiles {
            get {
                return ResourceManager.GetString("Overlay_FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Overlay_FilterPrograms {
            get {
                return ResourceManager.GetString("Overlay_FilterPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONE NAME.
        /// </summary>
        public static string Overlay_ZoneNamePlaceholder {
            get {
                return ResourceManager.GetString("Overlay_ZoneNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how to open items in overlays..
        /// </summary>
        public static string Settings_ClickModeHint {
            get {
                return ResourceManager.GetString("Settings_ClickModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLICK MODE.
        /// </summary>
        public static string Settings_ClickModeLabel {
            get {
                return ResourceManager.GetString("Settings_ClickModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click.
        /// </summary>
        public static string Settings_DoubleClick {
            get {
                return ResourceManager.GetString("Settings_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two clicks to open.
        /// </summary>
        public static string Settings_DoubleClickHint {
            get {
                return ResourceManager.GetString("Settings_DoubleClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large icons.
        /// </summary>
        public static string Settings_IconLarge {
            get {
                return ResourceManager.GetString("Settings_IconLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how items are displayed in overlays..
        /// </summary>
        public static string Settings_IconLayoutHint {
            get {
                return ResourceManager.GetString("Settings_IconLayoutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICON LAYOUT.
        /// </summary>
        public static string Settings_IconLayoutLabel {
            get {
                return ResourceManager.GetString("Settings_IconLayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Settings_IconList {
            get {
                return ResourceManager.GetString("Settings_IconList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small icons.
        /// </summary>
        public static string Settings_IconSmall {
            get {
                return ResourceManager.GetString("Settings_IconSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRAL MANAGER / SETTINGS.
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_Reset {
            get {
                return ResourceManager.GetString("Settings_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single click.
        /// </summary>
        public static string Settings_SingleClick {
            get {
                return ResourceManager.GetString("Settings_SingleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One click to open.
        /// </summary>
        public static string Settings_SingleClickHint {
            get {
                return ResourceManager.GetString("Settings_SingleClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the overlay behaviour..
        /// </summary>
        public static string Settings_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string ZoneCard_Active {
            get {
                return ResourceManager.GetString("ZoneCard_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string ZoneCard_Delete {
            get {
                return ResourceManager.GetString("ZoneCard_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FILES HERE.
        /// </summary>
        public static string ZoneCard_DropFilesHere {
            get {
                return ResourceManager.GetString("ZoneCard_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT ZONE.
        /// </summary>
        public static string ZoneCard_EditZone {
            get {
                return ResourceManager.GetString("ZoneCard_EditZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDBY.
        /// </summary>
        public static string ZoneCard_Standby {
            get {
                return ResourceManager.GetString("ZoneCard_Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Zone.
        /// </summary>
        public static string Zones_CreateZone {
            get {
                return ResourceManager.GetString("Zones_CreateZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Overlays.
        /// </summary>
        public static string Zones_HideOverlays {
            get {
                return ResourceManager.GetString("Zones_HideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRAL MANAGER / ACTIVE ZONES.
        /// </summary>
        public static string Zones_PageTitle {
            get {
                return ResourceManager.GetString("Zones_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Overlays.
        /// </summary>
        public static string Zones_ShowOverlays {
            get {
                return ResourceManager.GetString("Zones_ShowOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify your workspace by managing active zones..
        /// </summary>
        public static string Zones_Subtitle {
            get {
                return ResourceManager.GetString("Zones_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle or edit environments below..
        /// </summary>
        public static string Zones_ToggleHint {
            get {
                return ResourceManager.GetString("Zones_ToggleHint", resourceCulture);
            }
        }
    }
}
